name: Run Unit Tests
on:   
  pull_request:
    branches:
      - '**'
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run test